title: Computing in Context - ShefaaliD
author: ShefaaliD

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  config:
    # Enable heading anchors for cross-referencing
    myst_heading_anchors: 4
    # Include external JavaScript for interactive features
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    # Suppress specific warnings for unsupported MIME types
    suppress_warnings: ["mystnb.unknown_mime_type"]
